# Site settings
baseurl = "/showcases/"
languageCode = "en-us"
title = "Showcase of awesome projects for Flogo"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"

[params]
    # Meta
    siteAssetUrl = "/assets/"
    title = "Showcase"
    subtitle = "Showcase of awesome extensions and projects for Flogo!"
    author = "tibcosoftware"
    description = "Showcase of awesome extensions and projects for Flogo"

    # Preview container button text
    buttontext = "Get the project"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [aerohub](https://github.com/aerohub). Updated by [retgits](https://github.com/retgits)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
